---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - stx-kernel-upload-git-mirror

- job:
    name: stx-kernel-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/kernel to
      github.com/starlingx/kernel
    vars:
      git_mirror_repository: starlingx/kernel
    secrets:
      - name: git_mirror_credentials
        secret: stx-kernel-github-secret3
        pass-to-parent: true

- secret:
    name: stx-kernel-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - j5UxaG9yS6GbXGgGeJNt48H31ctzu2ddWXIJiXvhZu3QCRAFdomkQJu2h122vspUZ/jgM
          jn/QDDS10o3TWPTl67uZXz/QcJ2XHNJIR3PqHVOMwh7RoG0C9QWeu1ZIeW+wx4MFaDm9V
          h1fXfLkjY+QRWUqDgoKch+7bU4s+0+DHGoEGh95+iuIiZrcmSiEE/KryhMXqTFeD9hZ2C
          c4OuUnrDZ8wfrVz1efAvJ8kxuCd8QjOHeK9UAolQ8n6XV9okBxn2s+kOy5JX+1KeivjRf
          UHrd3XgXG5E4waz9lgMEW3yC2Sgph6R7XFXb3A6rHPNzbnNHRaY+gUO9KA6+pNvI3ad21
          gaaqdbdvWIEtyp7NDy9tqcgQl+l9vpkJI76vYLVI3MhiQeddbuI46d9xa1gXQUt3rgPm0
          pNzzM8X/+Xor56234T2RY1d4q3DaykCYI+iIjlvjfI0yCTgBxkCHI5KY4keoj8fZzcRpE
          nYSwFS4j3hOifb+ZtXXle7wXbajfCDcnMk8+n1tmYs3KSTx+jqEtlUR+6gSjO971n3rDH
          kSzeD5jIWFGViUReJafcPEDXbvjp4lmDAYBHdi1lqYdGy6iLVcviK0Xninl/ROd+R0rVe
          0YmRnpwvfTjZesmLMAui6sFmAYBNMqOs8rhliv30KZ7lrO6oJAcpwCLWPKrNPY=
        - K54qdrwLpbjN30j9uujETeJNuVEKJUBQ87bVrBLL/nWbi+Xhg7VwHjU55GZvWW7svY2ys
          y8UIUErrvZAnl6RdVnTr6Hl3uABHdRTy7Gn5PKcn0rj767MS8oy7SThJ14ryGkW3wV16v
          1ivgvJP2lvnFYcuuLTiLS2Li3WcapM9Bqa+scAc9uY8j7ZjM9YqxPstte19EkUHys5wcC
          cNziiE5EKhW352pZCqwuqos3/jw8nQoytgBi0CPUQtK2WpKWadlZlrNgKTO3oJH5sVjaQ
          x4wNHkamwtaCGHF9yzjpRVE2hoG00A+4USjx6hURIRmTqbd+M2u3ZOI9rXBuQpBcIK2BL
          BJNK4YbvInDBM/3LDHmUuMkCgMiY9xdyxaoHJEjDRsJgFhnpsTg/+vROYWY5PYhCrNiLf
          uAHH0kzyyANbu0doZ4F7NWPkqBtEcHHT5gzfoRg1Ra8JuhqXt8EAdHeyZ5UfrfTl6z/4I
          cyczQh1ZDF8fm35KBXyrGdEdZ8hLtzMKgeupKVBCFSUluZICkLRhGbdYzFjg0YCUExh5f
          xgP4nVIG4lVmo/E7x6LB8w4jpcZC7LWDb+NetVOLSot5viTMZyQfAldkWUISvuPOYRXrh
          yzFU0ifrPb/Yr6a/U4nAmcquZU8EX19TNYTIAYndI7B5Mmajl7cvovxXHlJugI=
        - nGWwSRhK8TSo5D8gv+71MsVAs7AzYH7aNjqinX3cQSpGy43gW64SOe2eYe48xtBbnP+2f
          hIdSwO5ILUile+NT6NgUiE35PCBdqULvgiGhXOlSzKOKDiz7gEMRTOqPczEKgA5Oifgos
          XFdR9KTBWR4ktrRC61UBNQia5AZQSvQfAz+bBi4VZ823lF9Om1/4XMLSF1ohYQi9nxQb8
          keGuPZkOIFkNRxUw0vJWCx/CXwZUgY8tSdr659+jyBJun/PbeFITe0gVB7Bcn8VBQyZvs
          wD61ymaEeylKiPq9dUWvccP4ZMa6HeG9ne0C5KD+jdzVw6Qx375PjaGadHVLvFbWbRTgP
          Ytw7INCT7yAmh7vWVEQ50jC+RvKVqB2V3LgjTbmuxkfyNUBQAC367ZZ4JKEJyq3NW08dy
          VfUQTds9EPBD5pXZ/5Bsm7+JKBm/JW/YR8Yg/F+9dtut5wa8DrlZ1jquTp3NXx3k/EDxs
          +k3hUJcDZwMYB6vl7vDJOCOljWj46Ncoe5rtbg83P06cQ7B/x5+vW/J8t5ErLDyqklJwl
          nYta07z+b+Zcj69hGDt27rtgJ0nS2OfZ0LrjVSZvC3keu1Vvzi7RbtzdOjwLusLV/He0Q
          kbY0qTWAe3IsH/Pb2SXOb2Q2fxf9EiSsdOduzGKQIsSqPslDdxwaJ0sBnDlVPg=
        - MeVOv0biuGCPj47Xq/B+M1oMCWcO6ARJOLf7qh1696QrR7+4knoA2bT9F0yOu3sBXKYz6
          KISYefhLkwl3YK20khjvH8m50zYfnHQ0CdWvrA/FME/g7bXNZupACIxBODvQyv3lpwwP6
          RZ0jsFhEOJDQxdnCUmzComYzcFq0TZO/PpKY/a9rJRlk7WjbuRme/c8xwSatbeAv8Vk34
          B0oHyFHFfSG307piT3520uJT6zSXPXPX818QFQCZLTAiTW/AERx5KZDZzh0kSEbslWdZE
          lv6Rkr7E0kii8rzQMHiTEGGdbaAghQjtEN9vjGl7vIfrJz7RDnVZrTa4UCdSeHQdPvAkg
          zRSUSHBkJATS87VBqBmtUb7tchsH2HN6SFZWYDhq+bYf+EGeOxMfPoDGQqv1myygI/kz9
          qqrp1VIVDOqFuR8FyuYkoag+mfbf532Yxp02dOrfli4ZrTSNwY8pH2nX9i79WGhL/Pk2+
          q4ZKxX/7+t4hXmkM2AzJy1PyiyJNmsrY9y7ZP/7ZQFQ/qB80mdxfoZAZ6HVsxZNlf5zeO
          dHNLyLTT84k943dC4upalqbCeZVGfZhl6O0zoFBIrlJky0U53KBVyQgYPCmCitFpZnPnx
          od9dnQ+ZxBLzm6NJip8a6lsYAMTAXm2rMEWZ94vVxI9S9YgEyqUgaI1QJEiV0A=
        - XP1qR2yYzFXAZ+1rffFO/VQ/U0Ovw2o6HQpaFVxz7NOo4oy+r7r6VFK/Kd74tMKL7BG6j
          lu03B9BGEv3+xHSU1HN3eJLpVM4FWFLqkEwjb9qzpKbs8INT/QXv6NLqoJZQSMhZLGFBm
          EBSA9x/yaZOonSRZekMm88sJbbjxSWJmzvzjNToG43mAb2X30yZRhlEHEFPKIsz+N0xKL
          x01GzWqRJHsEKde/+mt97ADcSRmqDUjDih7OOXprIwWWETBt+lyNqS5exIl5hMNpksw43
          f8clUAX5Lb2K1Zelw8Qf7xrnuO/ykWBXeQWjP7uvEM+jjL6fSug+aihZKrMh0xsQcSn+r
          FoekYgqrgOAJ1u3vE8ezebL/0hlKb+4BX2lWj3sVLc7OcTtgVUvMvRhncSXljnnG0Sz4S
          Ny2w8nsiMTUw+JIMTg08nEFDe8m3xwHlXsQ95v6f+V2Y8mLdMM6jpDh4q3C9BdMLGhRxn
          +oi9hHbGpIW3kQv7vyGxNfoARWnR+HrSJ4jF0nLmK3e+RnxPXezgyctANIh58rkBDr6sY
          s0KZXe7fPmLl/UrahfQSrlRQWwm+ZBoU7VWMPSSZ8nIPKNsuPm6VEYxCbK2EUM1lJE/GF
          o5H2hfKl2w2Kn94Y4dklUVpnSp1JNWMIW0P7iZa6WVH7Zvk31liPTi70fGFvNo=
        - fnBrc1SVSZgBRZlmVrJ0sUBRbBCQaTxkWPbHLoz0p1RWX1rxPUzsLcFV65gzue7LQYUsF
          eoAs8UetLSKlCot+zhDrGTevtZwz6WiGavxJTGo2ZZFymBrVjP2TG8rIf4kqu9qRXHLC6
          F5BuJQS6QcpiRfEm8Z57PS7vAnO8eEVrzu3PWUl30sfXkskA0RFRAfSyv9tl4KOH3GZ/s
          Pkbmv6vrqmL83eJnT8pQyW6/RKEj9MQ82ClW42NRaFfkYyHs/llgGjJM+voSd5Q+iE4J3
          Lv94zTt6nmIEEG74aAyNd9Ifi35LcAiD+l9nRBeA7k49DxmaohTav42G16GcoI/3aJ8+p
          fnqedIIfimX19VXCyFR+yHaXpHf90ngQTKp5PMu39FB4Uds5PndzKmrcKbvvETdwHBBrK
          HXumlBpgHR+Uut2C10vSONeorMjN1L04hsZ5QOFk7QzFivOvdbBJQE+3E7phCFuSbrc4v
          L+olAb3LOBG2I5ihVL9my+QT9lC95G8Wj597F557jYawOtvVjUJ9anj1EoFOsryjgC+TU
          wqlXWIu45X7/R0DpY6+DzwE6ZyEZIhoqKDXz5LCEeZyZGdzsD6DbgZpnocDRVLvn0j6kU
          ciuErD8b8CzG10bCnqxjHQHYX5/OFwSxnzBbqceVOcsMsTiPNCNHaysOhOdtT8=
        - jnkVfpQVaZbApiPcVq1jI5tDEzuiO3+Hz3Q9VlYZsQG11EhUnWFCushas4rBsZrTDAh9/
          /UWDzfL70tQRfDg4fQ/ot7jpLOpKHtqFZHRvoXVonj5ztmOmNim2n7BQIBSq6UnsZXoFY
          SCOLsM6lbt+PpEoC8qL4MYv9xGeJLST7BbqBwJLW+H6ksfGdwYHSHqU/3k/nkmHiEuU3K
          63AVPazsn+RYlz2fgFfSXCwd0mOokom2cy0FxxIar1HYbLIW4r9tz93pcbx5+2VYkaeEP
          OObyXDZKcMguh5RQxCs0Sdc1S/WpxKJ2X+S2GVZBQaVV7jwOBRTnxILcF69PFJyqUc2jC
          687lHOsgmkHDAVkoBHrG7KvNEp3meyrATiCs3lgyFgrkJ9mvk3lO+uyyUC5HLHQ8c87Iz
          b7lsnq1266pM4qhWbi/bInRNrwIl4kQ+C/DkpOpXgDojPiKNxJ8oUuRH7pGIC/94LbzNc
          2K2jW/hh5Jcmztjacyk+WZrhxiz/gwURxrsz5fIb79/7/lyk6JYIlyFa0pTMwITsjTXdB
          hj07yDv6FSTYbgxu+E/dEUWErIFv1Nepm67AMXciDWHIzJjFbOevGtnM2hZkKyhymTy6c
          NVAIJ73U/7CJegZb4b3M00VsJg0WpeubyxC2uPR8xq+unMw6yy3Orx9AeKFVv8=
