# List of packages to be included/installed in ISO

# bnxt_en - Broadcom kernel modules
bnxt-en
bnxt-en-rt

#intel-i40e
i40e
i40e-rt

#intel-iavf
iavf
iavf-rt

#intel-ice
ice
ice-rt

# Marvell kernel modules
octeon-ep
octeon-ep-rt

#intel-igb_uio
igb-uio
igb-uio-rt

#initramfs-trigger
initramfs-trigger

# libbnxt_re - Broadcom Infiniband verbs library
libbnxt-re

#kernel-std/kernel-rt
linux-headers-6.18.15+deb13-amd64
linux-rt-headers-6.18.15+deb13-rt-amd64
linux-headers-6.18.15+deb13-common
linux-rt-headers-6.18.15+deb13-rt-common
linux-image-6.18.15+deb13-amd64-unsigned
linux-rt-image-6.18.15+deb13-rt-amd64-unsigned
linux-kbuild-6.18.15+deb13
linux-rt-kbuild-6.18.15+deb13-rt
linux-libc-dev
linux-perf
linux-cpupower

#mlnx-ofa_kernel
mlnx-ofed-kernel-modules
mlnx-ofed-kernel-modules-rt
mlnx-ofed-kernel-utils

#rdma-core
ibacm
ibverbs-providers
ibverbs-utils
infiniband-diags
#libibmad-dev  # not used
libibmad5
#libibnetdisc-dev  # not used
libibnetdisc5
#libibumad-dev  # not used
libibumad3
#libibverbs-dev  # not used
libibverbs1
#librdmacm-dev  # not used
librdmacm1
python3-pyverbs
rdma-core
rdmacm-utils
srptools

#mstflint
mstflint

