# List of packages to be included/installed in ISO

# bnxt_en - Broadcom kernel modules
#bnxt-en
#bnxt-en-rt

#intel-i40e
i40e
i40e-rt

#intel-iavf
iavf
iavf-rt

#intel-ice
ice
ice-rt

# Marvell kernel modules
#octeon-ep
#octeon-ep-rt

#intel-igb_uio
igb-uio
igb-uio-rt

#initramfs-trigger
initramfs-trigger

# Intel Quartzville Linux Driver
iqvlinux
iqvlinux-rt

#intel-opae-fpgaa
kmod-opae-fpga-driver
kmod-opae-fpga-driver-rt

# libbnxt_re - Broadcom Infiniband verbs library
libbnxt-re

#kernel-std/kernel-rt
linux-compiler-gcc-10-x86
linux-headers-6.6.0-1-amd64
linux-rt-headers-6.6.0-1-rt-amd64
linux-headers-6.6.0-1-common
linux-rt-headers-6.6.0-1-rt-common
linux-image-6.6.0-1-amd64-unsigned
linux-rt-image-6.6.0-1-rt-amd64-unsigned
linux-kbuild-6.6
linux-rt-kbuild-6.6
linux-libc-dev
linux-perf

#mlnx-ofa_kernel
#mlnx-ofed-kernel-modules
#mlnx-ofed-kernel-modules-rt
#mlnx-ofed-kernel-utils

#qat20
#qat2.0.l
#qat2.0.l-rt

#rdma-core
ibacm
ibverbs-providers
ibverbs-utils
infiniband-diags
#libibmad-dev  # not used
libibmad5
#libibnetdisc-dev  # not used
libibnetdisc5
#libibumad-dev  # not used
libibumad3
#libibverbs-dev  # not used
libibverbs1
#librdmacm-dev  # not used
librdmacm1
python3-pyverbs
rdma-core
rdmacm-utils
srptools

#mstflint
mstflint

