#!/bin/bash

DOCA_PKG=doca-mlnx-ofed.tgz

tar zxvf ${DOCA_PKG}
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cd OFED-internal-debian-*/SOURCES
if [ $? -ne 0 ]
then
    echo "SOURCES failed: DOCA_PKG source!"
    exit 1
fi

cp mlnx-tools_*.orig.tar.gz ../../
tar zxvf mlnx-tools_*.orig.tar.gz
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cp -r mlnx-tools-2510.0.16 ../../mlnx-tools-3.2lts
