#!/bin/bash
#
# Copyright (c) 2026 Wind River Systems, Inc.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. The ASF licenses this
# file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# The only parameter is the name of the new directory that will contain
# the extracted source code. Be aware that this new directory will be
# created in the same directory as where this script is located when
# building.
# Tools needed: mkdir, rm, tar

set -e

DOCA_PKG=doca-mlnx-ofed.tgz

# Derive the version from local_debian/meta_data.yaml (debver)
META_DATA="$(cd "$(dirname "$0")" && pwd)"
YAML="$META_DATA/local_debian/meta_data.yaml"

DOCA_VERSION="$(awk -F': *' '/^debver:/ {gsub(/["'\'']/,"",$2); print $2; exit}' "$YAML")"
if [ -z "$DOCA_VERSION" ]; then
    echo "failed to read debver from ${YAML}!"
    exit 1
fi

mkdir MLNX_OFED_SRC
tar zxvf "${DOCA_PKG}" -C MLNX_OFED_SRC
if [ $? -ne 0 ]
then
    echo "tar failed: ${DOCA_PKG} !"
    exit 1
fi

mkdir MLNX_OFED_ORIG
cp MLNX_OFED_SRC/*/SOURCES/mlnx-ofed-kernel_*.orig.tar.gz .
tar zxvf mlnx-ofed-kernel_*.orig.tar.gz -C MLNX_OFED_ORIG
if [ $? -ne 0 ]
then
    echo "tar failed: MLNX_OFED_SRC!"
    exit 1
fi

mv MLNX_OFED_ORIG/mlnx-ofed-kernel* "doca-mlnx-ofed-${DOCA_VERSION}"
