#!/bin/bash

DOCA_PKG=doca-mlnx-ofed-3.3.0.tgz

tar zxvf ${DOCA_PKG}
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cd MLNX_OFED_SRC-26.01-1.0.0.0/SOURCES
if [ $? -ne 0 ]
then
    echo "SOURCES failed: DOCA_PKG source!"
    exit 1
fi

cp mlnx-ofed-kernel_26.01.OFED.26.01.1.0.0.1.orig.tar.gz ../../
tar zxvf mlnx-ofed-kernel_26.01.OFED.26.01.1.0.0.1.orig.tar.gz
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cp -r mlnx-ofed-kernel-26.01.OFED.26.01.1.0.0.1 ../../doca-mlnx-ofed-3.3.0
cp -r mlnx-ofed-kernel-26.01.OFED.26.01.1.0.0.1 ../../mlnx-ofed-kernel-26.01.OFED.26.01.1.0.0.1
