#!/bin/bash

DOCA_PKG=doca-mlnx-ofed.tgz

tar zxvf ${DOCA_PKG}
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cd OFED-internal-debian-25.10-2.4.1/SOURCES
if [ $? -ne 0 ]
then
    echo "SOURCES failed: DOCA_PKG source!"
    exit 1
fi

cp rdma-core_2510.0.11.orig.tar.gz ../../
tar zxvf rdma-core_2510.0.11.orig.tar.gz
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cp -r rdma-core-2510.0.11 ../../rdma-core-3.2lts
