#!/bin/bash

DOCA_PKG=doca-mlnx-ofed-3.3.0.tgz

tar zxvf ${DOCA_PKG}
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cd MLNX_OFED_SRC-26.01-1.0.0.0/SOURCES
if [ $? -ne 0 ]
then
    echo "SOURCES failed: DOCA_PKG source!"
    exit 1
fi

cp rdma-core_2601.0.7.orig.tar.gz ../../
tar zxvf rdma-core_2601.0.7.orig.tar.gz
if [ $? -ne 0 ]
then
    echo "tar failed: DOCA_PKG source!"
    exit 1
fi

cp -r rdma-core-2601.0.7 ../../doca-mlnx-rdma-core-3.3.0
