#!/bin/bash

# The only parameter is the name of the folder where the source code
# is extracted to. Pay attention to that the extracted package should
# be put at the same path where this script is located.
# Tools needed: unzip/rpm2cpio/cpio/md5sum

OPAE_PKG=OPAE_1.3.7-5_el7.zip
OPAE_VER=1.3.7-5
OPAE_MD5SUM=389888f2bb3e8cfb002a1ba880fc6823
OPAE_DRV=opae-intel-fpga-driver-2.0.1

wget https://github.com/OPAE/opae-sdk/releases/download/${OPAE_VER}/${OPAE_PKG}
if [ $? -ne 0 ]
then
    echo "wget failed: OPAE source!"
    exit 1
fi

md5sum ./${OPAE_PKG} | grep ${OPAE_MD5SUM}
if [ $? -ne 0 ]
then
    echo "Wrong md5sum: OPAE source!"
    exit 1
fi

unzip ./${OPAE_PKG}
if [ $? -ne 0 ]
then
    echo "unzip failed: OPAE source!"
    exit 1
fi

cd OPAE/source_code
rpm2cpio ${OPAE_DRV}-*.src.rpm | cpio -i
if [ $? -ne 0 ]
then
    echo "rpm2cpio/cpio failed: OPAE source!"
    exit 1
fi

tar zxvf ${OPAE_DRV}.tar.gz
if [ $? -ne 0 ]
then
    echo "tar failed: OPAE source!"
    exit 1
fi

mv ${OPAE_DRV} ../../$1
cd ../../
rm OPAE ${OPAE_PKG} -rf
