#!/bin/bash

# The only parameter is the name of the folder where the source code
# is extracted to. Pay attention to that the extracted package should
# be put at the same path where this script is located.
# Tools needed: tar

KERNEL_DIR=linux-6.18.15
DEBIAN_FILE=linux_6.18.15-1~bpo13%2B1.debian.tar.xz

tar xvf linux_6.18.15.orig.tar.xz
if [ $? -ne 0 ]
then
    echo "tar failed: linux kernel source!"
    exit 1
fi
mv ${KERNEL_DIR} $1

cd $1
tar xvf ../${DEBIAN_FILE}
if [ $? -ne 0 ]
then
    echo "tar failed: debian folder for kernel!"
    exit 1
fi
cd debian
cp "${MY_REPO_ROOT_DIR}"/cgcs-root/stx/kernel/kernel-rt/\
/debian/trixie/source/changelog ./
cp "${MY_REPO_ROOT_DIR}"/cgcs-root/stx/kernel/kernel-rt/\
/debian/trixie/source/config ./config/amd64/config.amd64

# The debian folder is written to build "linux". If use this folder
# to build similar things for kernel-rt, all the packages are renamed
# from "linux-xxx" to "linux-rt-xxx". Here replace those packages'
# name in those files of the debian folder which will affect building
cd ..
SED_LIST="./debian/bin ./debian/rules.d/tools/perf ./debian/rules ./debian/rules.real ./debian/signing_templates ./debian/templates ./debian/control"
grep -rl "linux-headers" $SED_LIST | xargs -r sed -i "s/linux-headers/linux-rt-headers/g"
grep -rl "linux-image" $SED_LIST | xargs -r sed -i "s/linux-image/linux-rt-image/g"
grep -rl "linux-perf" $SED_LIST | xargs -r sed -i "s/linux-perf/linux-rt-perf/g"
grep -rl "linux-config" $SED_LIST | xargs -r sed -i "s/linux-config/linux-rt-config/g"
grep -rl "linux-kbuild" $SED_LIST | xargs -r sed -i "s/linux-kbuild/linux-rt-kbuild/g"
grep -rl "linux-libc-dev" $SED_LIST | xargs -r sed -i "s/linux-libc-dev/linux-rt-libc-dev/g"
grep -rl "linux-source" $SED_LIST | xargs -r sed -i "s/linux-source/linux-rt-source/g"
grep -rl "linux-support" $SED_LIST | xargs -r sed -i "s/linux-support/linux-rt-support/g"

sed -i "s/^Source: linux$/Source: linux-rt/" ./debian/control
# Replace gcc-14-for-host with gcc-14 since we don't have that in our initramfs
sed -i "s/gcc-14-for-host /gcc-14 /g" ./debian/control

# Add linux-rt-keys to debian/control so it appears in the .dsc Binary field
# and the build scheduler can resolve dependency ordering
cat >> ./debian/control << 'EOF'

Package: linux-rt-keys
Architecture: linux-any
Depends: ${misc:Depends}
Multi-Arch: foreign
Description: Module signing keys for Linux RT kernel
EOF
