#!/bin/bash

# The only parameter is the name of the folder where the source code
# is extracted to. Pay attention to that the extracted package should
# be put at the same path where this script is located.
# Tools needed: tar

KERNEL_DIR=linux-6.18.15
DEBIAN_FILE=linux_6.18.15-1~bpo13%2B1.debian.tar.xz

tar xvf linux_6.18.15.orig.tar.xz
if [ $? -ne 0 ]
then
    echo "tar failed: linux kernel source!"
    exit 1
fi
mv ${KERNEL_DIR} $1

cd $1
tar xvf ../${DEBIAN_FILE}
if [ $? -ne 0 ]
then
    echo "tar failed: debian folder for kernel!"
    exit 1
fi

cd debian
cp "${MY_REPO_ROOT_DIR}"/cgcs-root/stx/kernel/kernel-std/\
/debian/trixie/source/changelog ./
cp "${MY_REPO_ROOT_DIR}"/cgcs-root/stx/kernel/kernel-std/\
/debian/trixie/source/config ./config/amd64/config.amd64
cd ..

# Replace gcc-14-for-host with gcc-14 since we don't have that in our initramfs
sed -i "s/gcc-14-for-host /gcc-14 /g" ./debian/control

# Add linux-keys to debian/control so it appears in the .dsc Binary field
# and the build scheduler can resolve dependency ordering
cat >> ./debian/control << 'EOF'

Package: linux-keys
Architecture: linux-any
Depends: ${misc:Depends}
Multi-Arch: foreign
Description: Module signing keys for Linux kernel
EOF
